# 线上配置文件
server:
  port: 8101
  address: 0.0.0.0
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.53.24:3306/ojstar
    username: ryan
    password: ryanpsw
  # Redis 配置
  # todo 需替换配置
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: ryanpsw
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: ryanpsw
# 代码沙箱配置
codesandbox:
  type: remote